name: national_sites_bulgaria_admin
description: Web panel for national sites in bulgaria - admin panel

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  provider: any
  shared_preferences: ^2.0.13
  get_it: ^7.2.0
  fluent_ui: any
  cached_network_image: ^3.1.1
  flutter_staggered_animations: ^1.0.0
  flutter_dotenv: ^5.0.2
  flutter_spinkit: ^5.1.0
  flutter_keyboard_visibility: any
  day_night_switcher: ^0.2.0+1
  json_serializable: ^6.1.0
  json_annotation: ^4.4.0
  lottie: ^1.2.2
  desktop_window: ^0.4.0
  fluttericon: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: 3.0.6
  firedart: ^0.9.0+1
  http: ^0.13.4
  timeago: ^3.2.2
  file_picker: ^4.6.1
  image_compression: ^1.0.3
  desktop_drop: ^0.3.3
  flutter_map: ^2.0.0
  blurhash_dart:
    git:
      url: https://github.com/justacid/blurhash-dart.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  build_runner: ^2.1.10
  msix: ^3.6.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - fonts/
    - .env

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

msix_config:
  display_name: National Sites - Admin
  publisher: CN=Kristiyan, O=AdminPanel
  install_certificate: false
  msix_version: 1.0.0.0
  capabilities: internetClient